### ISSUE TITLE
About the Environment

### ISSUE THREAD

**Issue by wanglincs** [ibgp2/ibgp2#4]
I wang to konw which your ubuntu version is. when I Install the project follwing the steps that provided，it said some error.

**Comment by ibgp2** [comment]
Hello @wanglincs,

I used Debian testing (I dont remember exactly what was the exact release 7 years ago).  I don't think the Debian release really matters. As Ubuntu is based on Debian, if you succeeded to install all the required package, this should not be the cause of the problem.

Howver, in 7 years, NS3 has probably evolved and maybe some classes have changed or disappeared.

Could you detail which commands you run and their corresponding output?

Best regards
